version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: supplier_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - db:/var/lib/mysql
    networks:
      - supplier-service-net

  supplier-service-app:
    container_name: supplier-service-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    networks:
      - supplier-service-net
    depends_on:
      - mysqldb

networks:
  supplier-service-net:

volumes:
  db: